import materialColors from './src/data/material-colors.json';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'media',
  mode: 'jit',
  content: ['./src/**/*.{html,ts,tsx}'],
  theme: {
    screens: {
      sm: '36rem',
      md: '48rem',
      lg: '62rem',
      xl: '75rem',
      xxl: '87.5rem',
    },
    extend: {
      colors: {
        ...materialColors,
        transparent: 'transparent',
        'off-white': '#F7F7F7',
      },
      borderRadius: {
        xs: '0.125rem',
        sm: '0.25rem',
        full: '100%',
      },
      spacing: {
        '1/12': '8.333333%',
        '2/12': '16.666667%',
        '3/12': '25%',
        '4/12': '33.333333%',
        '5/12': '41.666667%',
        '6/12': '50%',
        '7/12': '58.333333%',
        '8/12': '66.666667%',
        '9/12': '75%',
        '10/12': '83.333333%',
        '11/12': '91.666667%',
        full: '100%',
      },
      fontFamily: {
        body: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
    },
  },
  plugins: [],
};
